### ISSUE TITLE
Problem with Sync module (failed call to super)

### ISSUE THREAD

**Issue by LorenzoCavatorta** [mental32/spotify.py#15]
Hi!

I'm testing the flask example and I found this issue with the sync version of the library:
```
Python 3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spotify.sync as spotify
>>> spotify.Client('foo','bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lollo/.local/share/virtualenvs/spotinator-I8qC83Ee/lib/python3.7/site-packages/spotify/sync/models.py", line 81, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lollo/.local/share/virtualenvs/spotinator-I8qC83Ee/lib/python3.7/site-packages/spotify/client.py", line 61, in __init__
    self.http = self._default_http_client(client_id, client_secret, loop=loop)
  File "/home/lollo/.local/share/virtualenvs/spotinator-I8qC83Ee/lib/python3.7/site-packages/spotify/sync/models.py", line 20, in __init__
    super().__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
>>> 
```

explicitly specifying the base class seems to be fixing it ([like this](https://github.com/LorenzoCavatorta/spotify.py/commit/ff86179f4555b955981de33cce8e7de3de408f02#diff-9fb40c31fad6245487bb11ae6219bf1cL20)), but I'm not sure that's required.

**Comment by LorenzoCavatorta** [comment]
Hi, this is now working on v0.6.1
I'm however getting a similar error later on (when instantiating a User object). This is due to
[line 28](https://github.com/mental32/spotify.py/blob/v0.6.1/spotify/sync/models.py#L28)
