### ISSUE TITLE
When using album.get_all_tracks(), an error is produced. `'Nonetype' has no attribute 'images'`

### ISSUE THREAD

**Issue by aaronhnsy** [mental32/spotify.py#59]
Error is as the title says. Heres here traceback.
```
AttributeError: 'NoneType' object has no attribute 'images'
Traceback (most recent call last):
  File "C:\Users\mynam\Downloads\PycharmProjects\Life\venv\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\mynam\Downloads\PycharmProjects\Life\Life\cogs\voice\music.py", line 70, in play
    search_result = await ctx.player.get_results(ctx=ctx, search=search)
  File "C:\Users\mynam\Downloads\PycharmProjects\Life\Life\cogs\voice\utilities\player.py", line 97, in get_results
    spotify_tracks = await result.get_all_tracks()
  File "C:\Users\mynam\Downloads\PycharmProjects\Life\venv\lib\site-packages\spotify\models\album.py", line 125, in get_all_tracks
    return [track async for track in self]
  File "C:\Users\mynam\Downloads\PycharmProjects\Life\venv\lib\site-packages\spotify\models\album.py", line 125, in <listcomp>
    return [track async for track in self]
  File "C:\Users\mynam\Downloads\PycharmProjects\Life\venv\lib\site-packages\spotify\models\base.py", line 145, in __aiter__
    yield klass(client, item)  # pylint: disable=not-callable
  File "C:\Users\mynam\Downloads\PycharmProjects\Life\venv\lib\site-packages\spotify\models\track.py", line 78, in __init__
    self.images = album.images.copy()
```
I think this may be an api change as only a week ago with the same album this function worked normally, Now it is broken.

**Comment by mental32** [comment]
Thanks for reporting this!

will investigate this now :)

**Comment by aaronhnsy** [comment]
Hi, sorry for getting back to you late, this fix works fine thanks
