### ISSUE TITLE
aiohttp throws RuntimeError when running with Quart and ASGI server

### ISSUE THREAD

**Issue by sshamaiengar** [mental32/spotify.py#9]
I have created an API using Quart (async Flask) and spotify.py that has async functions as routes that make calls to `spotify.search`, `spotify.get_artist`, and other functions. When I run the API just using Quart, like with `app.run()`, everything works great. However, I am trying to deploy to Heroku, and in order to do that I need to use an ASGI web server called Hypercorn (similar to Gunicorn). When I run the API with hypercorn using `hypercorn src.wsgi:app` (where `src/wsgi.py` just contains an instance `app` of my API from a factory function), I get the following error on all routes:

```
ERROR in app: Exception on request GET /api/search/Drake
Traceback (most recent call last):
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/quart/app.py", line 1451, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/quart/app.py", line 1473, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/quart/app.py", line 892, in handle_user_exception
    raise error
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "/Users/shamaiengar/six-degrees-of-spotify/src/api.py", line 44, in search_artists
    results = await clients.spotify.search(artist_name, types=['artist'], limit="20")
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/spotify/client.py", line 256, in search
    data = await self.http.search(**kwargs)
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/spotify/http.py", line 123, in request
    self.bearer_info = bearer_info = await self.get_bearer_info()
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/spotify/http.py", line 103, in get_bearer_info
    async with self._session.post(**kwargs) as resp:
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/aiohttp/client.py", line 417, in _request
    with timer:
  File "/Users/shamaiengar/six-degrees-of-spotify/venv2/lib/python3.7/site-packages/aiohttp/helpers.py", line 568, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```

I am using spotify.py 0.4.8 and Python 3.7.4. Could I get some advice on how to fix this?

If you want to reproduce this error, you should be able to fork my repo [here](https://github.com/sshamaiengar/six-degrees-of-spotify), run the `hypercorn` command above, and try to access a route.

**Comment by mental32** [comment]
Thank you for reporting this, I'm currently Investigating.

As far as I can tell aiohttp is experiencing loop confusion when attempting to invoke the request.

I haven't used hypercorn but from what I've gathered its an asynchronous gunicorn? If this is the case then this can explain the loop confusion.

Also I've noticed that a potential fix could be if you simply created your `spotify.Client` instance inside a coroutine and that would resolve the confusion.

**Comment by sshamaiengar** [comment]
Yes, hypercorn is async gunicorn. 

> If this is the case then this can explain the loop confusion.

I don't know much about how event loops work so would you mind explaining this a bit more?

I am not sure how/where to create the spotify.Client inside a coroutine. Currently, it is created within my `create_app` factory function, which is synchronous and is what is passed to hypercorn to start a worker.

**Comment by mental32** [comment]
> I don't know much about how event loops work so would you mind explaining this a bit more?

The aiohttp session when created outside of a running event loop doesn't know which one it should attach itself to, so when one does start to perform operations over the session, the session's internals will appropriately detect something funky going on and panic, this can explain the `RuntimeError` you were catching. 

Off the top of my head a solution could be assigning the spotify client attribute on your quart server instance and set it to `None`. Then setup some sort of `before_request` handler and there you perform the check and construct the client when `app.spotify` is `None`

**Comment by sshamaiengar** [comment]
Using the `before_request` handler to initialize the Spotify client worked for me. Thanks for your help!
